# Generated by Django 5.0.6 on 2024-07-06 16:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("Perfiles", "0008_alter_paciente_perfil"),
    ]

    operations = [
        migrations.CreateModel(
            name="ResultadoPruebas",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tipo_prueba", models.CharField(max_length=255)),
                ("resultado", models.TextField()),
                ("fecha_realizacion", models.DateTimeField()),
                (
                    "perfil",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="resultados_pruebas",
                        to="Perfiles.perfil",
                    ),
                ),
            ],
        ),
    ]
