# Generated by Django 5.0.6 on 2024-07-07 07:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Perfiles", "0010_alter_enfermero_pacientes_alter_enfermero_perfil_and_more"),
        ("Staff", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="resultadopruebas",
            name="fecha_realizacion",
        ),
        migrations.AddField(
            model_name="resultadopruebas",
            name="medicos",
            field=models.ManyToManyField(
                related_name="resulados_pruebas", to="Perfiles.medico"
            ),
        ),
        migrations.CreateModel(
            name="Medicacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("medicina", models.CharField(max_length=255)),
                ("fecha_inicio", models.DateField()),
                ("fecha_final", models.DateField()),
                (
                    "medico",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="medicacion",
                        to="Perfiles.medico",
                    ),
                ),
                (
                    "perfil",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="medicacion",
                        to="Perfiles.perfil",
                    ),
                ),
            ],
        ),
    ]
