# Generated by Django 5.0.6 on 2024-07-19 07:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Staff", "0002_remove_resultadopruebas_fecha_realizacion_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="resultadopruebas",
            name="medicos",
        ),
        migrations.RemoveField(
            model_name="resultadopruebas",
            name="perfil",
        ),
        migrations.DeleteModel(
            name="Medicacion",
        ),
        migrations.DeleteModel(
            name="ResultadoPruebas",
        ),
    ]
