# Generated by Django 5.0.6 on 2024-07-19 07:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("Perfiles", "0014_remove_medico_enfermeros_alter_perfil_dni_and_more"),
        ("Staff", "0003_remove_resultadopruebas_medicos_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Medicacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("medicina", models.CharField(max_length=255)),
                ("fecha_inicio", models.DateField()),
                ("fecha_final", models.DateField()),
                (
                    "medico",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="medicacion",
                        to="Perfiles.medico",
                    ),
                ),
                (
                    "paciente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="medicacion",
                        to="Perfiles.paciente",
                    ),
                ),
            ],
        ),
    ]
