# Generated by Django 5.2.17 on 2026-09-05 14:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Perfiles', '0020_alter_medico_options_alter_paciente_options_and_more'),
        ('Staff', '0004_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='medicacion',
            options={'ordering': ['-fecha_inicio'], 'verbose_name': 'medicación', 'verbose_name_plural': 'medicaciones'},
        ),
        migrations.AddField(
            model_name='medicacion',
            name='dosis',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='medicacion',
            name='instrucciones',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='medicacion',
            name='medicina',
            field=models.CharField(max_length=255, verbose_name='medicamento'),
        ),
        migrations.AlterField(
            model_name='medicacion',
            name='medico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='medicacion', to='Perfiles.medico'),
        ),
        migrations.AlterField(
            model_name='medicacion',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicacion', to='Perfiles.paciente'),
        ),
    ]
