# Generated by Django 5.0.6 on 2024-07-06 16:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("Perfiles", "0008_alter_paciente_perfil"),
    ]

    operations = [
        migrations.CreateModel(
            name="Visita",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("hora_fecha", models.DateTimeField(default="2000-01-01 00:00:00")),
                ("descripcion_problema", models.TextField()),
                (
                    "medico",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="Visita",
                        to="Perfiles.medico",
                    ),
                ),
                (
                    "paciente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="Visita",
                        to="Perfiles.paciente",
                    ),
                ),
            ],
        ),
    ]
