# Generated by Django 5.0.6 on 2024-07-07 17:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Pacientes", "0002_alter_visita_medico_alter_visita_paciente"),
    ]

    operations = [
        migrations.AlterField(
            model_name="visita",
            name="hora_fecha",
            field=models.DateTimeField(
                blank=True, default="2000-01-01 00:00:00", null=True
            ),
        ),
    ]
