# Generated by Django 5.0.6 on 2024-07-07 17:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Pacientes", "0003_alter_visita_hora_fecha"),
        ("Perfiles", "0010_alter_enfermero_pacientes_alter_enfermero_perfil_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="visita",
            name="medico",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="visita",
                to="Perfiles.medico",
            ),
        ),
        migrations.AlterField(
            model_name="visita",
            name="paciente",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="visita",
                to="Perfiles.paciente",
            ),
        ),
    ]
