# Generated by Django 5.0.6 on 2024-07-07 17:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Pacientes", "0004_alter_visita_medico_alter_visita_paciente"),
    ]

    operations = [
        migrations.AlterField(
            model_name="visita",
            name="hora_fecha",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
