# Generated by Django 5.2.17 on 2026-09-05 14:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pacientes', '0005_alter_visita_hora_fecha'),
        ('Perfiles', '0020_alter_medico_options_alter_paciente_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='visita',
            options={'ordering': ['-hora_fecha'], 'verbose_name_plural': 'visitas'},
        ),
        migrations.AddField(
            model_name='visita',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('realizada', 'Realizada'), ('cancelada', 'Cancelada')], default='pendiente', max_length=10),
        ),
        migrations.AlterField(
            model_name='visita',
            name='descripcion_problema',
            field=models.TextField(verbose_name='motivo de la consulta'),
        ),
        migrations.AlterField(
            model_name='visita',
            name='hora_fecha',
            field=models.DateTimeField(blank=True, null=True, verbose_name='fecha y hora'),
        ),
        migrations.AlterField(
            model_name='visita',
            name='medico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='visita', to='Perfiles.medico'),
        ),
        migrations.AlterField(
            model_name='visita',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visita', to='Perfiles.paciente'),
        ),
    ]
