# Generated by Django 5.0.6 on 2024-07-04 16:57

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Paciente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("contacto_emergencia", models.CharField(max_length=255)),
                ("telefono_emergencia", models.CharField(max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name="Enfermero",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "pacientes",
                    models.ManyToManyField(
                        related_name="Enfermero", to="Perfiles.paciente"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Perfil",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "access_key",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("nombre", models.CharField(max_length=255)),
                ("apellido", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=254)),
                ("telefono", models.CharField(max_length=12)),
                ("direccion", models.CharField(max_length=255)),
                ("fecha_nacimiento", models.DateField()),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="perfil",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="paciente",
            name="perfil",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="Paciente",
                to="Perfiles.perfil",
            ),
        ),
        migrations.CreateModel(
            name="Medico",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "enfermeros",
                    models.ManyToManyField(
                        related_name="Medico", to="Perfiles.enfermero"
                    ),
                ),
                (
                    "pacientes",
                    models.ManyToManyField(
                        related_name="Medico", to="Perfiles.paciente"
                    ),
                ),
                (
                    "perfil",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="Medico",
                        to="Perfiles.perfil",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="enfermero",
            name="perfil",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="Enfermero",
                to="Perfiles.perfil",
            ),
        ),
    ]
