# Generated by Django 5.0.6 on 2024-07-04 17:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Perfiles", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="medico",
            name="enfermeros",
            field=models.ManyToManyField(
                blank=True, null=True, related_name="Medico", to="Perfiles.enfermero"
            ),
        ),
        migrations.AlterField(
            model_name="medico",
            name="pacientes",
            field=models.ManyToManyField(
                blank=True, null=True, related_name="Medico", to="Perfiles.paciente"
            ),
        ),
    ]
