# Generated by Django 5.0.6 on 2024-07-04 17:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Perfiles", "0002_alter_medico_enfermeros_alter_medico_pacientes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="enfermero",
            name="pacientes",
            field=models.ManyToManyField(
                blank=True, null=True, related_name="Enfermero", to="Perfiles.paciente"
            ),
        ),
        migrations.AlterField(
            model_name="paciente",
            name="contacto_emergencia",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="paciente",
            name="telefono_emergencia",
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
