# Generated by Django 5.0.6 on 2024-07-05 08:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Perfiles", "0005_alter_perfil_groups"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="perfil",
            name="groups",
        ),
    ]
