# Generated by Django 5.0.6 on 2024-07-05 15:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Perfiles", "0006_remove_perfil_groups"),
    ]

    operations = [
        migrations.AddField(
            model_name="perfil",
            name="numero_seguro_social",
            field=models.CharField(default="", max_length=20, unique=True),
        ),
    ]
