# Generated by Django 5.0.6 on 2024-07-05 20:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Perfiles", "0007_perfil_numero_seguro_social"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paciente",
            name="perfil",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="Pacientes",
                to="Perfiles.perfil",
            ),
        ),
    ]
