# Generated by Django 5.0.6 on 2024-07-06 16:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Perfiles", "0008_alter_paciente_perfil"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="medico",
            name="pacientes",
        ),
        migrations.AddField(
            model_name="paciente",
            name="medicos",
            field=models.ManyToManyField(
                related_name="pacientes", to="Perfiles.medico"
            ),
        ),
    ]
