# Generated by Django 5.0.6 on 2024-07-07 07:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Perfiles", "0009_remove_medico_pacientes_paciente_medicos"),
    ]

    operations = [
        migrations.AlterField(
            model_name="enfermero",
            name="pacientes",
            field=models.ManyToManyField(
                blank=True, null=True, related_name="enfermero", to="Perfiles.paciente"
            ),
        ),
        migrations.AlterField(
            model_name="enfermero",
            name="perfil",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="enfermero",
                to="Perfiles.perfil",
            ),
        ),
        migrations.AlterField(
            model_name="medico",
            name="enfermeros",
            field=models.ManyToManyField(
                blank=True, null=True, related_name="medico", to="Perfiles.enfermero"
            ),
        ),
        migrations.AlterField(
            model_name="medico",
            name="perfil",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="medico",
                to="Perfiles.perfil",
            ),
        ),
        migrations.AlterField(
            model_name="paciente",
            name="perfil",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pacientes",
                to="Perfiles.perfil",
            ),
        ),
    ]
