# Generated by Django 5.0.6 on 2024-07-12 15:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Perfiles", "0010_alter_enfermero_pacientes_alter_enfermero_perfil_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="perfil",
            name="dni",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
