# Generated by Django 5.0.6 on 2024-07-08 15:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Perfiles", "0010_alter_enfermero_pacientes_alter_enfermero_perfil_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paciente",
            name="medicos",
            field=models.ManyToManyField(
                blank=True, null=True, related_name="pacientes", to="Perfiles.medico"
            ),
        ),
    ]
