# Generated by Django 5.0.6 on 2024-07-12 15:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Perfiles", "0011_perfil_dni"),
    ]

    operations = [
        migrations.AlterField(
            model_name="perfil",
            name="dni",
            field=models.CharField(default="0000000F", max_length=20),
        ),
    ]
