# Generated by Django 5.0.6 on 2024-07-17 15:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Perfiles", "0011_alter_paciente_medicos"),
        ("Perfiles", "0012_alter_perfil_dni"),
    ]

    operations = []
