# Generated by Django 5.0.6 on 2024-07-19 07:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Enfermedades", "0005_remove_cancermama_diagnostico_and_more"),
        ("Perfiles", "0013_merge_20240717_1703"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="medico",
            name="enfermeros",
        ),
        migrations.AlterField(
            model_name="perfil",
            name="dni",
            field=models.CharField(max_length=9),
        ),
        migrations.DeleteModel(
            name="Enfermero",
        ),
    ]
