# Generated by Django 5.0.6 on 2024-07-21 15:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Perfiles", "0014_remove_medico_enfermeros_alter_perfil_dni_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="medico",
            name="perfil",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="medico",
                to="Perfiles.perfil",
            ),
        ),
        migrations.AlterField(
            model_name="paciente",
            name="medicos",
            field=models.ManyToManyField(
                blank=True, related_name="pacientes", to="Perfiles.medico"
            ),
        ),
        migrations.AlterField(
            model_name="paciente",
            name="perfil",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="pacientes",
                to="Perfiles.perfil",
            ),
        ),
        migrations.AlterField(
            model_name="perfil",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="perfil",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
