# Generated by Django 5.0.7 on 2024-07-24 17:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Perfiles', '0015_alter_medico_perfil_alter_paciente_medicos_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('especialidad', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('telefono', models.CharField(max_length=12)),
                ('medico', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_profile', to='Perfiles.medico')),
            ],
        ),
    ]
