# Generated by Django 5.0.7 on 2024-07-24 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Perfiles', '0016_doctorprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DoctorProfile',
        ),
    ]
