# Generated by Django 5.0.7 on 2024-07-26 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Perfiles', '0018_alter_perfil_apellido_alter_perfil_direccion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='numero_seguro_social',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
