# Generated by Django 5.2.17 on 2026-09-05 14:14

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Perfiles', '0019_alter_perfil_numero_seguro_social'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='medico',
            options={'ordering': ['perfil__apellido', 'perfil__nombre'], 'verbose_name_plural': 'médicos'},
        ),
        migrations.AlterModelOptions(
            name='paciente',
            options={'ordering': ['perfil__apellido', 'perfil__nombre']},
        ),
        migrations.AlterModelOptions(
            name='perfil',
            options={'ordering': ['apellido', 'nombre'], 'verbose_name_plural': 'perfiles'},
        ),
        migrations.AddField(
            model_name='medico',
            name='especialidad',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='medico',
            name='numero_colegiado',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='medico',
            name='perfil',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='medico', to='Perfiles.perfil'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='perfil',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='paciente', to='Perfiles.perfil'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='telefono_emergencia',
            field=models.CharField(blank=True, max_length=12, null=True, validators=[django.core.validators.RegexValidator('^\\+?[0-9\\s]{7,15}$', 'Introduce un teléfono válido (7-15 dígitos, opcionalmente con prefijo +).')]),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='dni',
            field=models.CharField(max_length=9, validators=[django.core.validators.RegexValidator('^[0-9]{7,8}[A-Za-z]?$', 'Introduce un DNI válido: 7 u 8 dígitos y, opcionalmente, la letra.')]),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='telefono',
            field=models.CharField(blank=True, max_length=12, null=True, validators=[django.core.validators.RegexValidator('^\\+?[0-9\\s]{7,15}$', 'Introduce un teléfono válido (7-15 dígitos, opcionalmente con prefijo +).')]),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL),
        ),
    ]
