# Generated by Django 5.0.6 on 2024-07-19 07:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("Perfiles", "0014_remove_medico_enfermeros_alter_perfil_dni_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Expediente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha_hora", models.DateTimeField(blank=True, null=True)),
                ("antecedentes", models.TextField()),
                (
                    "especialidad",
                    models.CharField(
                        choices=[
                            ("CancerMama", "Cáncer de Mama"),
                            ("Diabetes", "Diabetes"),
                            ("Pneumonia", "Neumonía"),
                            ("Lunares", "Lunares"),
                            ("Cardiaco", "Cardiaco"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "doctor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="expediente",
                        to="Perfiles.medico",
                    ),
                ),
                (
                    "paciente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="expediente",
                        to="Perfiles.perfil",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="temporal_expediente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha_hora", models.DateTimeField(blank=True, null=True)),
                ("antecedentes", models.TextField()),
                (
                    "especialidad",
                    models.CharField(
                        choices=[
                            ("CancerMama", "Cáncer de Mama"),
                            ("Diabetes", "Diabetes"),
                            ("Pneumonia", "Neumonía"),
                            ("Lunares", "Lunares"),
                            ("Cardiaco", "Cardiaco"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "doctor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="temporal_expediente",
                        to="Perfiles.medico",
                    ),
                ),
                (
                    "paciente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="temporal_expediente",
                        to="Perfiles.perfil",
                    ),
                ),
            ],
        ),
    ]
