# Generated by Django 5.0.6 on 2024-07-21 15:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Perfiles", "0015_alter_medico_perfil_alter_paciente_medicos_and_more"),
        ("expedientes", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="expediente",
            name="doctor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="expediente",
                to="Perfiles.medico",
            ),
        ),
        migrations.AlterField(
            model_name="expediente",
            name="especialidad",
            field=models.CharField(
                blank=True,
                choices=[
                    ("CancerMama", "Cáncer de Mama"),
                    ("Diabetes", "Diabetes"),
                    ("Pneumonia", "Neumonía"),
                    ("Lunares", "Lunares"),
                    ("Cardiaco", "Cardiaco"),
                ],
                max_length=50,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="expediente",
            name="paciente",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="expediente",
                to="Perfiles.perfil",
            ),
        ),
        migrations.AlterField(
            model_name="temporal_expediente",
            name="doctor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="temporal_expediente",
                to="Perfiles.medico",
            ),
        ),
        migrations.AlterField(
            model_name="temporal_expediente",
            name="especialidad",
            field=models.CharField(
                blank=True,
                choices=[
                    ("CancerMama", "CancerMama"),
                    ("Diabetes", "Diabetes"),
                    ("Pneumonia", "Neumonía"),
                    ("Lunares", "Lunares"),
                    ("Cardiaco", "Cardiaco"),
                ],
                max_length=50,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="temporal_expediente",
            name="paciente",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="temporal_expediente",
                to="Perfiles.perfil",
            ),
        ),
    ]
