# Generated by Django 5.0.6 on 2024-07-21 19:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Perfiles", "0015_alter_medico_perfil_alter_paciente_medicos_and_more"),
        ("expedientes", "0002_alter_expediente_doctor_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="expediente",
            name="paciente",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="expediente",
                to="Perfiles.paciente",
            ),
        ),
        migrations.AlterField(
            model_name="temporal_expediente",
            name="paciente",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="temporal_expediente",
                to="Perfiles.paciente",
            ),
        ),
    ]
