# Generated by Django 5.0.6 on 2024-07-21 20:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("expedientes", "0003_alter_expediente_paciente_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="expediente",
            old_name="paciente",
            new_name="pacientes",
        ),
    ]
