# Generated by Django 5.0.6 on 2024-07-21 20:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("expedientes", "0004_rename_paciente_expediente_pacientes"),
    ]

    operations = [
        migrations.RenameField(
            model_name="expediente",
            old_name="pacientes",
            new_name="paciente",
        ),
    ]
