# Generated by Django 5.2.17 on 2026-09-05 14:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Perfiles', '0020_alter_medico_options_alter_paciente_options_and_more'),
        ('expedientes', '0005_rename_pacientes_expediente_paciente'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expediente',
            options={'ordering': ['-fecha_hora'], 'verbose_name_plural': 'expedientes'},
        ),
        migrations.AddField(
            model_name='expediente',
            name='diagnostico',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='expediente',
            name='tratamiento',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='expediente',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expediente', to='Perfiles.medico'),
        ),
        migrations.AlterField(
            model_name='expediente',
            name='especialidad',
            field=models.CharField(blank=True, choices=[('CancerMama', 'Cáncer de mama'), ('Diabetes', 'Diabetes'), ('Pneumonia', 'Neumonía'), ('Lunares', 'Lunares / melanoma'), ('Cardiaco', 'Cardiología'), ('Tuberculosis', 'Tuberculosis'), ('TumorCerebral', 'Tumor cerebral')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='expediente',
            name='fecha_hora',
            field=models.DateTimeField(blank=True, null=True, verbose_name='fecha y hora'),
        ),
        migrations.AlterField(
            model_name='expediente',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expediente', to='Perfiles.paciente'),
        ),
        # Se renombra el modelo en lugar de borrarlo y recrearlo: así los
        # borradores existentes no se pierden al migrar.
        migrations.RenameModel(
            old_name='temporal_expediente',
            new_name='TemporalExpediente',
        ),
        migrations.AlterModelOptions(
            name='temporalexpediente',
            options={'ordering': ['-fecha_hora'], 'verbose_name': 'expediente temporal', 'verbose_name_plural': 'expedientes temporales'},
        ),
        migrations.AlterField(
            model_name='temporalexpediente',
            name='fecha_hora',
            field=models.DateTimeField(blank=True, null=True, verbose_name='fecha y hora'),
        ),
        migrations.AlterField(
            model_name='temporalexpediente',
            name='especialidad',
            field=models.CharField(blank=True, choices=[('CancerMama', 'Cáncer de mama'), ('Diabetes', 'Diabetes'), ('Pneumonia', 'Neumonía'), ('Lunares', 'Lunares / melanoma'), ('Cardiaco', 'Cardiología'), ('Tuberculosis', 'Tuberculosis'), ('TumorCerebral', 'Tumor cerebral')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='temporalexpediente',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='temporal_expediente', to='Perfiles.medico'),
        ),
        migrations.AlterField(
            model_name='temporalexpediente',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='temporal_expediente', to='Perfiles.paciente'),
        ),
    ]
