# Generated by Django 5.0.6 on 2024-07-06 16:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("Perfiles", "0008_alter_paciente_perfil"),
    ]

    operations = [
        migrations.CreateModel(
            name="Diagnostico",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "paciente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="diagnosticos",
                        to="Perfiles.paciente",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CancerMama",
            fields=[
                (
                    "diagnostico_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="Enfermedades.diagnostico",
                    ),
                ),
                ("estadio", models.CharField(max_length=50)),
                ("receptor_hormonal", models.BooleanField(default=False)),
            ],
            bases=("Enfermedades.diagnostico",),
        ),
        migrations.CreateModel(
            name="Cardiaco",
            fields=[
                (
                    "diagnostico_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="Enfermedades.diagnostico",
                    ),
                ),
                ("tipo", models.CharField(max_length=50)),
                ("tratamiento", models.TextField(blank=True, null=True)),
                ("fecha_ultima_revision", models.DateField(default="2000-01-01")),
            ],
            bases=("Enfermedades.diagnostico",),
        ),
        migrations.CreateModel(
            name="Diabetes",
            fields=[
                (
                    "diagnostico_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="Enfermedades.diagnostico",
                    ),
                ),
                ("tipo", models.CharField(max_length=50)),
                ("nivel_glucosa", models.FloatField()),
            ],
            bases=("Enfermedades.diagnostico",),
        ),
        migrations.CreateModel(
            name="Lunares",
            fields=[
                (
                    "diagnostico_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="Enfermedades.diagnostico",
                    ),
                ),
                ("localizacion", models.CharField(max_length=255)),
                ("tipo", models.CharField(max_length=50)),
                ("tamano", models.FloatField()),
            ],
            bases=("Enfermedades.diagnostico",),
        ),
        migrations.CreateModel(
            name="Pneumonia",
            fields=[
                (
                    "diagnostico_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="Enfermedades.diagnostico",
                    ),
                ),
                ("gravedad", models.CharField(max_length=50)),
                ("tratamiento", models.TextField(blank=True, null=True)),
            ],
            bases=("Enfermedades.diagnostico",),
        ),
    ]
