# Generated by Django 5.0.6 on 2024-07-07 07:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Enfermedades", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cardiaco",
            name="diagnostico_ptr",
        ),
        migrations.RemoveField(
            model_name="diabetes",
            name="diagnostico_ptr",
        ),
        migrations.RemoveField(
            model_name="diagnostico",
            name="paciente",
        ),
        migrations.RemoveField(
            model_name="pneumonia",
            name="diagnostico_ptr",
        ),
        migrations.RemoveField(
            model_name="lunares",
            name="diagnostico_ptr",
        ),
        migrations.DeleteModel(
            name="CancerMama",
        ),
        migrations.DeleteModel(
            name="Cardiaco",
        ),
        migrations.DeleteModel(
            name="Diabetes",
        ),
        migrations.DeleteModel(
            name="Pneumonia",
        ),
        migrations.DeleteModel(
            name="Diagnostico",
        ),
        migrations.DeleteModel(
            name="Lunares",
        ),
    ]
