# Generated by Django 5.0.6 on 2024-07-07 07:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("Enfermedades", "0002_remove_cardiaco_diagnostico_ptr_and_more"),
        ("Perfiles", "0010_alter_enfermero_pacientes_alter_enfermero_perfil_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Diagnostico",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "medico",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="diagnosticos",
                        to="Perfiles.medico",
                    ),
                ),
                (
                    "paciente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="diagnosticos",
                        to="Perfiles.paciente",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Diabetes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tipo", models.CharField(max_length=50)),
                ("nivel_glucosa", models.FloatField()),
                (
                    "diagnostico",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="diabetes",
                        to="Enfermedades.diagnostico",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Cardiaco",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tipo", models.CharField(max_length=50)),
                ("tratamiento", models.TextField(blank=True, null=True)),
                ("fecha_ultima_revision", models.DateField(default="2000-01-01")),
                (
                    "diagnostico",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="cardiaco",
                        to="Enfermedades.diagnostico",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CancerMama",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("estadio", models.CharField(max_length=50)),
                ("receptor_hormonal", models.BooleanField(default=False)),
                (
                    "diagnostico",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="cancer_mama",
                        to="Enfermedades.diagnostico",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Lunares",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("localizacion", models.CharField(max_length=255)),
                ("tipo", models.CharField(max_length=50)),
                ("tamano", models.FloatField()),
                (
                    "diagnostico",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="lunares",
                        to="Enfermedades.diagnostico",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Pneumonia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("gravedad", models.CharField(max_length=50)),
                ("tratamiento", models.TextField(blank=True, null=True)),
                (
                    "diagnostico",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="pneumonia",
                        to="Enfermedades.diagnostico",
                    ),
                ),
            ],
        ),
    ]
