# Generated by Django 5.0.6 on 2024-07-09 08:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Enfermedades", "0003_initial"),
        ("Perfiles", "0011_alter_paciente_medicos"),
    ]

    operations = [
        migrations.CreateModel(
            name="Analisis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tipo_analisis", models.CharField(max_length=255)),
                ("fecha_realizacion", models.DateField()),
                ("resultado", models.TextField()),
                (
                    "enfermero",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="Analisis",
                        to="Perfiles.enfermero",
                    ),
                ),
                (
                    "medico",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="Analisis",
                        to="Perfiles.medico",
                    ),
                ),
                (
                    "paciente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="Analisis",
                        to="Perfiles.paciente",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Vacuna",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre_vacuna", models.CharField(max_length=255)),
                ("fecha_administracion", models.DateField()),
                ("dosis", models.CharField(max_length=50)),
                (
                    "enfermero",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="Vacuna",
                        to="Perfiles.enfermero",
                    ),
                ),
                (
                    "medico",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="Vacuna",
                        to="Perfiles.medico",
                    ),
                ),
                (
                    "paciente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="Vacuna",
                        to="Perfiles.paciente",
                    ),
                ),
            ],
        ),
    ]
