# Generated by Django 5.0.6 on 2024-07-19 07:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Enfermedades", "0004_analisis_vacuna"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cancermama",
            name="diagnostico",
        ),
        migrations.RemoveField(
            model_name="cardiaco",
            name="diagnostico",
        ),
        migrations.RemoveField(
            model_name="diabetes",
            name="diagnostico",
        ),
        migrations.RemoveField(
            model_name="diagnostico",
            name="medico",
        ),
        migrations.RemoveField(
            model_name="diagnostico",
            name="paciente",
        ),
        migrations.RemoveField(
            model_name="lunares",
            name="diagnostico",
        ),
        migrations.RemoveField(
            model_name="pneumonia",
            name="diagnostico",
        ),
        migrations.RemoveField(
            model_name="vacuna",
            name="enfermero",
        ),
        migrations.RemoveField(
            model_name="vacuna",
            name="medico",
        ),
        migrations.RemoveField(
            model_name="vacuna",
            name="paciente",
        ),
        migrations.DeleteModel(
            name="Analisis",
        ),
        migrations.DeleteModel(
            name="CancerMama",
        ),
        migrations.DeleteModel(
            name="Cardiaco",
        ),
        migrations.DeleteModel(
            name="Diabetes",
        ),
        migrations.DeleteModel(
            name="Lunares",
        ),
        migrations.DeleteModel(
            name="Diagnostico",
        ),
        migrations.DeleteModel(
            name="Pneumonia",
        ),
        migrations.DeleteModel(
            name="Vacuna",
        ),
    ]
