# Generated by Django 5.0.6 on 2024-07-19 07:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("Enfermedades", "0005_remove_cancermama_diagnostico_and_more"),
        ("expedientes", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CancerMama",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "imagen",
                    models.ImageField(blank=True, upload_to="cancer_mama_images/"),
                ),
                (
                    "expediente",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="expedientes.expediente",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Cardiaco",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("estado_salud", models.IntegerField()),
                ("revision_medica", models.IntegerField()),
                ("ejercicio", models.IntegerField()),
                ("enfermedad_cardiaca", models.IntegerField()),
                ("cancer_piel", models.IntegerField()),
                ("otros_cancer", models.IntegerField()),
                ("depresion", models.IntegerField()),
                ("diabetes", models.IntegerField()),
                ("artritis", models.IntegerField()),
                ("genero", models.IntegerField()),
                ("categoria_edad", models.IntegerField()),
                ("altura", models.DecimalField(decimal_places=2, max_digits=5)),
                ("peso", models.DecimalField(decimal_places=2, max_digits=5)),
                (
                    "bmi",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=5),
                ),
                ("historial_fumador", models.CharField(max_length=3)),
                (
                    "consumo_alcohol",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                ("consumo_frutas", models.DecimalField(decimal_places=2, max_digits=5)),
                (
                    "consumo_vegetales",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                (
                    "consumo_papas_fritas",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                (
                    "expediente",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="expedientes.expediente",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Diabetes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("genero", models.CharField(max_length=6)),
                ("edad", models.DecimalField(decimal_places=2, max_digits=5)),
                ("hipertension", models.IntegerField()),
                ("ataques_cardiacos", models.IntegerField()),
                ("historial_fumador", models.CharField(max_length=7)),
                ("bmi", models.DecimalField(decimal_places=2, max_digits=5)),
                ("nivel_hba1c", models.DecimalField(decimal_places=2, max_digits=4)),
                ("glucosa_sangre", models.IntegerField()),
                ("diabetes", models.IntegerField()),
                (
                    "expediente",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="expedientes.expediente",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Lunares",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "imagen",
                    models.ImageField(
                        blank=True, null=True, upload_to="lunares_images/"
                    ),
                ),
                (
                    "expediente",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="expedientes.expediente",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Pneumonia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "imagen",
                    models.ImageField(
                        blank=True, null=True, upload_to="pneumonia_images/"
                    ),
                ),
                (
                    "expediente",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="expedientes.expediente",
                    ),
                ),
            ],
        ),
    ]
