# Generated by Django 5.0.6 on 2024-07-21 15:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Enfermedades", "0006_initial"),
        ("expedientes", "0002_alter_expediente_doctor_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cancermama",
            name="expediente",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="expedientes.expediente",
            ),
        ),
        migrations.AlterField(
            model_name="cardiaco",
            name="expediente",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="expedientes.expediente",
            ),
        ),
        migrations.AlterField(
            model_name="diabetes",
            name="expediente",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="expedientes.expediente",
            ),
        ),
        migrations.AlterField(
            model_name="lunares",
            name="expediente",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="expedientes.expediente",
            ),
        ),
        migrations.AlterField(
            model_name="pneumonia",
            name="expediente",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="expedientes.expediente",
            ),
        ),
    ]
