# Generated by Django 5.2.17 on 2026-09-05 14:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Enfermedades', '0007_alter_cancermama_expediente_and_more'),
        ('expedientes', '0006_alter_expediente_options_expediente_diagnostico_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cancermama',
            options={'verbose_name': 'cáncer de mama', 'verbose_name_plural': 'cánceres de mama'},
        ),
        migrations.AlterModelOptions(
            name='cardiaco',
            options={'verbose_name': 'caso cardíaco', 'verbose_name_plural': 'casos cardíacos'},
        ),
        migrations.AlterModelOptions(
            name='diabetes',
            options={'verbose_name_plural': 'diabetes'},
        ),
        migrations.AlterModelOptions(
            name='lunares',
            options={'verbose_name': 'lunar', 'verbose_name_plural': 'lunares'},
        ),
        migrations.AlterModelOptions(
            name='pneumonia',
            options={'verbose_name': 'neumonía', 'verbose_name_plural': 'neumonías'},
        ),
        migrations.AlterField(
            model_name='cancermama',
            name='expediente',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='expedientes.expediente'),
        ),
        migrations.AlterField(
            model_name='cardiaco',
            name='altura',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='altura (cm)'),
        ),
        migrations.AlterField(
            model_name='cardiaco',
            name='bmi',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='IMC'),
        ),
        migrations.AlterField(
            model_name='cardiaco',
            name='categoria_edad',
            field=models.IntegerField(verbose_name='categoría de edad'),
        ),
        migrations.AlterField(
            model_name='cardiaco',
            name='depresion',
            field=models.IntegerField(verbose_name='depresión'),
        ),
        migrations.AlterField(
            model_name='cardiaco',
            name='expediente',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='expedientes.expediente'),
        ),
        migrations.AlterField(
            model_name='cardiaco',
            name='genero',
            field=models.IntegerField(verbose_name='género'),
        ),
        migrations.AlterField(
            model_name='cardiaco',
            name='peso',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='peso (kg)'),
        ),
        migrations.AlterField(
            model_name='diabetes',
            name='ataques_cardiacos',
            field=models.BooleanField(default=False, verbose_name='cardiopatía previa'),
        ),
        migrations.AlterField(
            model_name='diabetes',
            name='bmi',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='IMC'),
        ),
        migrations.AlterField(
            model_name='diabetes',
            name='diabetes',
            field=models.BooleanField(default=False, verbose_name='diagnóstico positivo'),
        ),
        migrations.AlterField(
            model_name='diabetes',
            name='expediente',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='expedientes.expediente'),
        ),
        migrations.AlterField(
            model_name='diabetes',
            name='genero',
            field=models.CharField(choices=[('Mujer', 'Mujer'), ('Hombre', 'Hombre'), ('Otro', 'Otro')], max_length=10),
        ),
        migrations.AlterField(
            model_name='diabetes',
            name='glucosa_sangre',
            field=models.IntegerField(verbose_name='glucosa en sangre'),
        ),
        migrations.AlterField(
            model_name='diabetes',
            name='hipertension',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='diabetes',
            name='historial_fumador',
            field=models.CharField(choices=[('never', 'Nunca'), ('current', 'Fumador actual'), ('former', 'Exfumador'), ('No Info', 'Sin información')], max_length=10),
        ),
        migrations.AlterField(
            model_name='diabetes',
            name='nivel_hba1c',
            field=models.DecimalField(decimal_places=2, max_digits=4, verbose_name='nivel HbA1c'),
        ),
        migrations.AlterField(
            model_name='lunares',
            name='expediente',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='expedientes.expediente'),
        ),
        migrations.AlterField(
            model_name='pneumonia',
            name='expediente',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='expedientes.expediente'),
        ),
    ]
